### ISSUE TITLE
Support for statsd tags

### ISSUE THREAD

**Issue by sumedhsakdeo** [vthiery/cpp-statsd-client#11]
We were wondering if tags are supported by this client library and how they should be used. 
We are looking something similar to python statsd client metrics tagging feature
```
    import statsd
    c = statsd.StatsClient('localhost', 8125, prefix='foo')
    c.incr('bar', tags = {"key1": "value1", "key2":"value2"})
```
As discussed here https://stackoverflow.com/questions/49852654/sending-statsd-metrics-with-tags-from-python-client

**Comment by vthiery** [comment]
Hi,

Tags are not yet supported by this client. I suppose we could support tags in the same way [this Go client](https://godoc.org/github.com/smira/go-statsd#Client.Incr) does, maybe using templates.

Unfortunately, I won't have the time to work on this right now, but PRs are very welcome.

**Comment by vthiery** [comment]
@kevinkreiser I reopened this issue since tags support is also a requirement for your use-case
