### ISSUE TITLE
Cleanup: Run Linter in CI

### ISSUE THREAD

**Issue by kevinkreiser** [vthiery/cpp-statsd-client#22]
Currently CI does not check for properly linted code. We use clang-format here with the checked in style but we dont validate it on CI which makes for a bunch of work for any reviewer to sift through. To save some work, lets have the computers do it for us and run lint and fail the build if doing so shows any differences with what is checked in.

Also differences in versions of clang-format will do different things with your style file. Should we pin the version to avoid that problem?

**Comment by vthiery** [comment]
Yes good point, we should check the style via CI (and pin the clang-format version if possible).

**Comment by vthiery** [comment]
I'll look into this one
