### ISSUE TITLE
Cleanup: CMake Doesn't Export the Library as an Interface

### ISSUE THREAD

**Issue by kevinkreiser** [vthiery/cpp-statsd-client#23]
At the moment the cmake setup we have works to build the test program but there are a couple of minor issues with it:

1. the test program doesnt `depend` on the library (because there is no library target) and so you can get in a situation where you make changes to the header and the test program isnt able to tell it needs to be rebuilt
2. depending on how someone wants to use this library in a downstream project they may need to do some tricks. we should create a library target and mark it as an interface so that downstream users via cmake will know where to look for includes (this includes the test executable as well)
3. we dont set a version or a description
4. other little stuff?

**Comment by vthiery** [comment]
I'm very rusty with cmake configuration so I trust you on this. If you want to work on this, feel free, otherwise I'll need some time to dig into it.

**Comment by kevinkreiser** [comment]
oh sorry im happy to work on all of these issues that im creating, please feel free to assing me to any/all of them :smile:
