### ISSUE TITLE
Add cpp-statsd-client to the public conan repo?

### ISSUE THREAD

**Issue by hestad** [vthiery/cpp-statsd-client#7]
Would it be much work to add this lib to the public conan repo?

**Comment by vthiery** [comment]
Hi @hestad! I actually already started the process to have the package in Conan Center quite some time ago. The conan admins are quite busy checking the packages it seems. I just sent a new message to know where it stands and will keep you updated!

**Comment by vthiery** [comment]
The library is now packaged and available in the conan-center remote :)
